import {
  Award,
  BarChart3,
  BookOpen,
  Calculator,
  CheckCheck,
  Clock,
  Download,
  Eye,
  FileSearch,
  FileSignature,
  Filter,
  GitCompare,
  History,
  ListOrdered,
  Mail,
  PenLine,
  ShieldAlert,
  Sigma,
  Store,
  Table2,
  Wrench,
  type LucideIcon,
} from "lucide-react";

// One icon per Lens tool, for "What Lens did".
const ICONS: Record<string, LucideIcon> = {
  get_comparison: Table2,
  filter_suppliers: Filter,
  rank_lines: ListOrdered,
  supplier_totals: Sigma,
  compute_scenario: Calculator,
  compare_scenarios: GitCompare,
  compare_last_cycle: History,
  get_freshness: Clock,
  list_blockers: ShieldAlert,
  get_award_status: Award,
  get_source: FileSearch,
  draft_clarification: Mail,
  send_clarification: Mail,
  make_chart: BarChart3,
  export: Download,
  accept_values: CheckCheck,
  set_view: Eye,
  choose_scenario_and_draft_memo: FileSignature,
  get_purchase_history: History,
  get_meridian_standards: BookOpen,
  get_suppliers: Store,
  update_rfx_draft: PenLine,
};

export const toolIcon = (name: string): LucideIcon => ICONS[name] ?? Wrench;
